services:
  - type: web
    name: AluAsistencias-Backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
